version: '3.8'
services:
  mongo-db:
    image: mongo:6.0.6
    container_name: mongo-db
    restart: always
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db

  cinema-server:
    image: arieldocker24/cinema-server:latest
    build: ./backend/cinema-server
    container_name: cinema-server
    restart: always
    env_file:
      - ./backend/cinema-server/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongo-db
      - subscriptions-server
    networks:
      - app-network

  subscriptions-server:
    image: arieldocker24/subscriptions-server:latest
    build: ./backend/subscriptions-server
    container_name: subscriptions-server
    restart: always
    env_file:
      - ./backend/subscriptions-server/.env
    depends_on:
      - mongo-db
    networks:
      - app-network

  cinema-app:
    image: arieldocker24/cinema-app:latest
    build: ./client
    container_name: cinema-app
    restart: always
    ports:
      - "80:80"
    depends_on:
      - cinema-server
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge