name: Docker CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: push docker image to docker hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          docker-compose version
      
      - name: Login to docker hub
        env:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
        run: |
            echo $password | docker login -u $username --password-stdin

      - name: Build the docker image
        run: |
            ls -la 
            docker-compose build

      - name: Tag Docker images for Docker Hub
        run: |
          docker tag cinema-server ${{secrets.DOCKERHUB_USERNAME}}/cinema-server:latest
          docker tag subscriptions-server ${{secrets.DOCKERHUB_USERNAME}}/subscriptions-server:latest
          docker tag cinema-app ${{secrets.DOCKERHUB_USERNAME}}/cinema-app:latest

      - name: Push Docker images to Docker Hub
        run: |
          docker push ${{secrets.DOCKERHUB_USERNAME}}/cinema-server:latest
          docker push ${{secrets.DOCKERHUB_USERNAME}}/subscriptions-server:latest
          docker push ${{secrets.DOCKERHUB_USERNAME}}/cinema-app:latest
